const nav = document.createElement('nav');
const brand = document.createElement('a');
const row = document.createElement('div');
const casesWrapper = document.createElement('div');
const casesGlobal = document.createElement('div');
const casesBy = document.createElement('div');
const mapWrapper = document.createElement('div');
const map = document.createElement('div');
const statWrapper = document.createElement('div');
const dateStat = document.createElement('div');
const graphicStat = document.createElement('div');
nav.classList = 'navbar navbar-expand-lg bg-warning';
brand.classList = 'navbar-brand';
brand.innerText = 'COVID 19/20';
row.classList = 'd-flex flex-wrap main';
casesWrapper.classList = 'col-lg-2 p-0';
casesGlobal.classList = 'm-3 bg-warning cases-30';
casesBy.classList = 'm-3 bg-warning cases-70';
mapWrapper.classList = 'col-lg-7 p-0';
statWrapper.classList = 'col-lg-3 p-0';
map.classList = 'p-3 my-3 bg-warning map-100';
dateStat.classList = 'p-3 m-3 bg-warning stat-50';
graphicStat.classList = 'p-3 m-3 bg-warning stat-50';
casesWrapper.append(casesGlobal, casesBy);
row.append(casesWrapper, mapWrapper);
mapWrapper.appendChild(map);
statWrapper.append(dateStat, graphicStat);
row.appendChild(statWrapper);
nav.appendChild(brand);
document.body.append(nav, row);
document.body.classList = 'bg-dark';
window.casesGlobal = casesGlobal;
window.casesBy = casesBy;
window.map = map;
window.dateStat = dateStat;
window.graphicStat = graphicStat;
